### ISSUE TITLE
Should one expect these scripts work on a Linux system?

### ISSUE THREAD

**Issue by pcardout** [matthewrenze/powerpoint-to-pdf#3]
Thank you for providing this project.  I need to upgrade my system to run a more modern python (shown below).
I was concerned that comtypes might only run on a Windows system  ... but it seemed to install OK.
Can you specify in your readme if you expect this to run on a Linux system?  I can test it for you and report once I finish
my upgrade.

xxx@yyy:~$ pip3 install comtypes
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Collecting comtypes
  Downloading comtypes-1.1.10.tar.gz (145 kB)
     |████████████████████████████████| 145 kB 543 kB/s 
Building wheels for collected packages: comtypes
...
Successfully installed comtypes-1.1.10

**Comment by matthewrenze** [comment]
@pcardout I've never tried running it on a Linux system. Honestly, I would be a bit surprised if it works given that it relies on older COM components. However, I'm surprised by how far we've come with cross-platform compatibility in recent years. If it does work for you, please let me know and I'll update the read.me file to indicate that it should run on Linux systems as well as Windows.

**Comment by sandeepy0** [comment]
> @pcardout I've never tried running it on a Linux system. Honestly, I would be a bit surprised if it works given that it relies on older COM components. However, I'm surprised by how far we've come with cross-platform compatibility in recent years. If it does work for you, please let me know and I'll update the read.me file to indicate that it should run on Linux systems as well as Windows.

Hello @matthewrenze ,
Yes, it does not work in linux.
